"""Generate embeddedCharacters.ts with raw RGBA pixel data for synchronous loading."""
import base64, os
try:
    from PIL import Image
except ImportError:
    print("ERROR: PIL not installed. Run: pip install Pillow")
    exit(1)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHARS_DIR = os.path.join(ROOT, "webview-ui", "public", "assets", "characters")
OUT_PATH = os.path.join(ROOT, "webview-ui", "src", "office", "sprites", "embeddedCharacters.ts")

lines = [
    "// Auto-generated by scripts/gen_embedded_chars.py — DO NOT EDIT.",
    "// Embedded character sprites as raw RGBA pixel data for SYNCHRONOUS loading.",
    "// This bypasses ALL async image loading (new Image(), createImageBitmap, decode()).",
    "// The webview uses putImageData() at module init time — fully synchronous.",
    "",
]

names = ["char_employeeA", "char_employeeB"]
for name in names:
    path = os.path.join(CHARS_DIR, f"{name}.png")
    img = Image.open(path).convert("RGBA")
    width, height = img.size
    
    # Get raw RGBA bytes
    rgba_bytes = img.tobytes()
    
    # Base64 encode the raw RGBA data
    b64 = base64.b64encode(rgba_bytes).decode("ascii")
    
    key = name.replace("char_employee", "")
    lines.append(f"// {name}: {width}×{height} = {len(rgba_bytes)} bytes RGBA")
    lines.append(f'export const CHAR_{key}_RGBA = "{b64}";')
    lines.append(f'export const CHAR_{key}_WIDTH = {width};')
    lines.append(f'export const CHAR_{key}_HEIGHT = {height};')
    lines.append("")

lines.append("export const EMBEDDED_CHARACTERS: Array<{")
lines.append("  id: string;")
lines.append("  width: number;")
lines.append("  height: number;")
lines.append("  rgbaBase64: string;")
lines.append("}> = [")
lines.append('  { id: "char_employeeA", width: CHAR_A_WIDTH, height: CHAR_A_HEIGHT, rgbaBase64: CHAR_A_RGBA },')
lines.append('  { id: "char_employeeB", width: CHAR_B_WIDTH, height: CHAR_B_HEIGHT, rgbaBase64: CHAR_B_RGBA },')
lines.append("];")
lines.append("")

output = "\n".join(lines)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(output)
print(f"Wrote {len(output)} chars to {OUT_PATH}")
print(f"Generated {len(names)} character sheets with raw RGBA data")
